services:
  app:
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_SUPABASE_URL: "${VITE_SUPABASE_URL}"
        VITE_SUPABASE_ANON_KEY: "${VITE_SUPABASE_ANON_KEY}"
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production