version: '3.8'

volumes:
  db_data:

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: movtracker
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: movtracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Database connection URL for local Postgres
      - DATABASE_URL=postgresql://movtracker:secret@db:5432/movtracker
    depends_on:
      - db