// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmvkybinmfonxctjltwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtdmt5YmlubWZvbnhjdGpsdHdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNjA0MzQsImV4cCI6MjA1NzgzNjQzNH0.lBALOpj2fGFQ7MEfJQbxX7V9DPQBBh2CoFgT9iYJm0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);